export enum AppRoutes {
  LOGIN = '/login',
  REGISTER = '/register',
  PROFILE = '/profile',
  GROUPS = '/groups',
  USERS = '/users',
  COMPANITES = '/companies',
  SEASONS = '/seasons',
  SEASON = '/seasons/:id',
  SEMESTER = '/semesters/:id',
  SEMESTERS = '/semesters',
  CHATS = '/chats',
  CHAT = '/chats/:id',
  MENU = '/',
}
